import './globals.css'
import Sidebar from './components/Sidebar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className='bg-gray-800'>
      <body className='flex'>
        <Sidebar></Sidebar>
        <main className='ml-40 mt-5 text-white'>{children}</main>
      </body>
    </html>
  )
}
